SELECT name FROM sys.databases;

USE master;
GO
ALTER DATABASE HM_STAG_ETL_DB SET OFFLINE WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE HM_STAG_ETL_DB;
GO

USE master;
GO
ALTER DATABASE HM_DWH_ETL_DB SET OFFLINE WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE HM_DWH_ETL_DB;
GO


CREATE DATABASE HM_STAG_ETL_DB
ON 
(
    FILENAME = 'G:\SSIS_ETL_PROJECTS\DBs\HM_STAG_ETL_DB.mdf'
)
LOG ON
(
    FILENAME = 'G:\SSIS_ETL_PROJECTS\DBs\HM_STAG_ETL_DB_log.ldf'
)
FOR ATTACH;
GO


CREATE DATABASE HM_DWH_ETL_DB
ON 
(
    FILENAME = 'G:\SSIS_ETL_PROJECTS\DBs\HM_DWH_ETL_DB.mdf'
)
LOG ON
(
    FILENAME = 'G:\SSIS_ETL_PROJECTS\DBs\HM_DWH_ETL_DB_log.ldf'
)
FOR ATTACH;
GO
